language: python
install:
   - pip install sphinx
script:
   - make html
   - make singlehtml
   - make epub
   - rm .gitignore # if not removed, built pages don't get pushed to gh-pages
deploy:
   provider: pages
   skip-cleanup: true
   github-token: $GITHUB_TOKEN
   keep-history: true
   on:
     branch: master
