language: python
install:
   - pip install sphinx
script:
   - make html
   - make singlehtml
   - make epub
deploy:
   provider: pages
   skip-cleanup: true
   github-token: $GITHUB_TOKEN
   keep-history: true
   on:
     branch: master
# https://docs.travis-ci.com/user/deployment/pages/
